### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sameerz**
Correcting a URL link for Bullet documentation.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by akshaisarma** [comment]
@sameerz Thanks! I can merge this in after you accept the CLA.

**Comment by sameerz** [comment]
Accepted the CLA

**Comment by akshaisarma** [comment]
Hmm, the status check is still failing but this is not really a code change, so I'll merge it in.

**Pull request merged**
